
# TODO: need to do this for both "getmac" and "get-mac" packages
# TODO: don't publish pre-releases OR publish them as pre-releases to PyPI

# name: "Build and publish a release"

# on:
#   release:
#     types: [released]

# jobs:
#   publish:
#     name: "ğŸ“¦ Publish Python distributions"
#     runs-on: "ubuntu-latest"
#     strategy:
#       matrix:
#         python-version:
#           - "3.8"
#     steps:
#       - uses: "actions/checkout@master"
#       - name: "ğŸ Set up Python ${{ matrix.python-version }}"
#         uses: "actions/setup-python@v2"
#         with:
#           python-version: "${{ matrix.python-version }}"
#       - name: "ğŸ Display Python version"
#         run: "python --version"
#       - name: "ğŸ Install wheel"
#         run: "python -m pip install wheel --user"
#       - name: "ğŸ Build a binary wheel and a source tarball"
#         run: "python setup.py sdist bdist_wheel"
#       - name: "ğŸ“¦ Publish distribution to PyPI"
#         uses: "pypa/gh-action-pypi-publish@master"
#         if: "startsWith(github.ref, 'refs/tags')"
#         with:
#           password: "${{ secrets.pypi_password }}"
